services:
  postgres:
    image: postgres:16
    container_name: backend-api-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: backend_api
      POSTGRES_USER: backend_user
      POSTGRES_PASSWORD: backend_password
    volumes:
      - backend_api_postgres_data:/var/lib/postgresql/data

volumes:
  backend_api_postgres_data: